### ISSUE TITLE
Failed to get claims JWT:square/go-jose: error in cryptographic primitive

### ISSUE THREAD

**Issue by Excel1** [tbaehler/gin-keycloak#12]
I successfully like the idea and try to use the library by my own as gin middleware to secure endpoint "/v2/a". The Webservice starts and i call the endpoint by using postman with the oAuth2 Token in the Authorization Header i got the following errors (also by using the new version from the #11 

Also i got only a empty response with no error message.

 ```
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /v2/a                     --> treasurer/handler.ServiceInfo (5 handlers)
[GIN-debug] POST   /v1/account               --> treasurer/handler.CreateAccount (4 handlers)
[GIN-debug] POST   /v1/team                  --> treasurer/handler.CreateTeam (4 handlers)
[GIN-debug] GET    /v1/a                     --> treasurer/handler.ServiceInfo (4 handlers)
[GIN-debug] Listening and serving HTTP on :8081
ERROR: logging before flag.Parse: E0622 14:15:56.656280   78270 gin_keycloak.go:106] Failed to get publickey no key found
ERROR: logging before flag.Parse: E0622 14:15:56.656475   78270 gin_keycloak.go:150] [Gin-OAuth] Can not extract TokenContainer, caused by: no key found
[GIN] 2021/06/22 - 14:15:56 | 401 |  557.796962ms |             ::1 | GET      "/v2/a"
Error #01: No token in context
```

**Comment by tbaehler** [comment]
to be able to validate your jwt access token. ginkeycloak needs the signing public key from your keycloack provider.

Check your config, specially Url and Realm. 

      ginkeycloak.BuilderConfig{
		Service:              failIfEmpty(viper.GetString("oauth.service"), "oauth service"),
		Url:                      failIfEmpty(viper.GetString("oauth.url"), "oauth url"),
		Realm:                failIfEmpty(viper.GetString("oauth.realm"), "oauth realm"),
		DisableSecurityCheck: viper.GetBool("oauth.disabled"),
	}
	
ginKeycloack searches for your pubkey at

url := config.Url + "/auth/realms/" + config.Realm + "/protocol/openid-connect/certs

if you enter this url in your browser you should be able to get your public keys
it should look something like this..

{"keys":[{"kid":".......","kty":"RSA","alg":"RS256","use":"sig","n":"....","e":"...","x5c":["..."}]}

**Comment by Excel1** [comment]
thanks for the fast reply. Yes its my fault i got a typo... sorry :(

Now (with hopefully) the right settings i got:
```
ERROR: logging before flag.Parse: E0622 15:31:49.607074   80913 gin_keycloak.go:120] Failed to get claims JWT:square/go-jose: error in cryptographic primitive
ERROR: logging before flag.Parse: E0622 15:31:49.607247   80913 gin_keycloak.go:150] [Gin-OAuth] Can not extract TokenContainer, caused by: square/go-jose: error in cryptographic primitive
[GIN] 2021/06/22 - 15:31:49 | 401 |   354.83994ms |             ::1 | GET      "/v2/a"
Error #01: No token in context
```

**Comment by tbaehler** [comment]
looks like a problem with jour jwt token. do you have a kid defined? and the pub key with this id is available? can you post your jwt token you try to validate?

**Comment by Excel1** [comment]
I dont know what you mean with kid defined. Im using Keycloak with the default Client-Settings. The public keys are accessible under ../protocol/openid-connect/certs

`
eyJhbGciOiJFUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJRZk9CMEdUQVlsMHYtWDlRdlc1Rmp3TkdrZTdkemNVLTBQRmpwT0MxRThrIn0.eyJqdGkiOiIzNjNmOTYxMy1kYjMwLTRmY2QtYWQxYS03ZWI2MmM0Nzk2NzEiLCJleHAiOjE2MjQ0NzI1MzUsIm5iZiI6MCwiaWF0IjoxNjI0NDcyMjM1LCJpc3MiOiJodHRwczovL2F1dGguamstcG93ZXJlZC5kZS9hdXRoL3JlYWxtcy9jb25uZWN0IiwiYXVkIjpbIm5leHRjbG91ZCIsIm1hdG9tby1qayIsIndvcmRwcmVzcy1pbWtlcmVpLW1vbHMiLCJhY2NvdW50Iiwid29yZHByZXNzLWprIl0sInN1YiI6IjRiMjIwYzM2LTk5ZWUtNDRlZS04MzRkLWQwMTBmMmVkMzk0NiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFwaS10b2tlbiIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6ImNhNzM0YTM4LTcxNmItNDVlMC04MzUwLTU1YjAzM2E1MTc2YSIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im5leHRjbG91ZCI6eyJyb2xlcyI6WyJ1c2VyIl19LCJtYXRvbW8tamsiOnsicm9sZXMiOlsiZGV2ZWxvcGVyIl19LCJ3b3JkcHJlc3MtaW1rZXJlaS1tb2xzIjp7InJvbGVzIjpbImRldmVsb3BlciJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19LCJ3b3JkcHJlc3MtamsiOnsicm9sZXMiOlsiZGV2ZWxvcGVyIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiSmFubmlrIEtvbHRob2YiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqay5mdHAuamtAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6Ikphbm5payIsImZhbWlseV9uYW1lIjoiS29sdGhvZiIsImVtYWlsIjoiamsuZnRwLmprQGdtYWlsLmNvbSJ9.58a3YHmlZh1RXzc6GAVoJ-0VM8kfuxoG6mYEqIr0KkK7iMKaowMJRJdoM_gUo9J3F25BtyjirywcksR3Zrcq5w
`

**Comment by tbaehler** [comment]
Ah I see you are using a EC Key type (Ecliptic Curve)... 

{"kid":"QfOB0GTAYl0v-X9QvW5FjwNGke7dzcU-0PFjpOC1E8k","kty":"EC","alg":"ES256","use":"sig","crv":"P-256","x":"IrJt3yBDKpQC560X_-gl68m3lhe_yga39DX4VIEUCSc","y":"fVxSGVuLqvLzzteDVejXwTy7pPOER_oLZZk-Yk6cwos"}

for your JWT.

At the moment only RSA is supported, but I am keen to support EC Keys as well. 
I will come up with a patch that supports EC Key's as well. 
Hopefully today....

**Comment by Excel1** [comment]
I tested it with RS512 and it works successfully! Thanks for help!

Maybe it is nicer if it also outputs a json error message than just an empty response like: 
`
{ 
"code": "403"
"message": "forbidden"
}
`
Should we add the supported algorithms in the Documentation? (Readme)

And is there a way to get the information from the claims? Like sub, preferred_username or email? (If yes should we add this to the documentation? :) )

**Comment by tbaehler** [comment]
Please update to version 1.2

    go get -u github.com/tbaehler/gin-keycloak
    
It should work for you

**Comment by tbaehler** [comment]
token is available in the gin context under name this should work

ginToken,_ := context.Get("token")
token = ginToken.(ginkeycloak.KeyCloakToken)

yes please create a PR with an updated readme

**Comment by Excel1** [comment]
Thank you so much! It works finally!
I will create a PR with an updated readme.
