### ISSUE TITLE
getPublicKeyFromCacheOrBackend fails when the Keycloak instance is run in a container

### ISSUE THREAD

**Issue by liaozhai** [tbaehler/gin-keycloak#15]
I have detected that the "/auth/realms/{myrealm}/protocol/openid-connect/certs" request fails, while "/realms/{myrealm}/protocol/openid-connect/certs" works perfectly. For unknown reasons the official Keycloak Docker image is configured somehow differently and contrary to the REST API documentation has a different path scheme. I have not yet found a workaround for the problem. Perhaps it would be good if we could have possibility to configure Keycloak endpoints, particularly the endpoint in question, which is now hard-coded. 
![Screenshot 2022-03-16 173542](https://user-images.githubusercontent.com/6428672/158614489-255bdf2b-f9ba-4cac-9cd1-be28dd8446a2.png)

**Comment by tbaehler** [comment]
Thanks for asking this feature request. I made it happen.
Please update to version 1.3.0 and try this. 

ginkeycloak.NewAccessBuilder(ginkeycloak.BuilderConfig{FullCertsPath: &path}).Build()

let me know if it worked for you.

**Comment by liaozhai** [comment]
Yep. It works. Thanks a lot!
