### ISSUE TITLE
Please create a tag that includes CustomClaimsMapper

### ISSUE THREAD

**Issue by develmac** [tbaehler/gin-keycloak#17]
Dear maintainers, 

would it be possible (as it is better for reproducible builds) to have a tag that contains the CustomClaimsMapper feature?

As far as I can see it, the lasest (v1.3.0) does not include it. 

THX! 

MaC

**Comment by mkumatag** [comment]
I also need the latest tagged version to use with latest keycloak version where path got changed(right now pulling the master commit)

**Comment by tbaehler** [comment]
Sorry for long delay. You find v1.4.0 now in the repo

**Comment by mkumatag** [comment]
> Sorry for long delay. You find v1.4.0 now in the repo

cool, I see the new tag now.. thanks a lot @tbaehler :)
