### ISSUE TITLE
gin-keycloakv1.5.0 uses github.com/gin-gonic/gin@v1.7.7 which has an open cve

### ISSUE THREAD

**Issue by yossich6** [tbaehler/gin-keycloak#19]
In issue https://github.com/tbaehler/gin-keycloak/issues/18 it was updated that it was fixed but the github.com/gin-gonic/gin@v1.7.7 still appears in go mod.

see https://github.com/tbaehler/gin-keycloak/blob/master/go.mod line 4

**Comment by tbaehler** [comment]
https://github.com/tbaehler/gin-keycloak/blob/v1.5.0/go.mod

please try to update again

**Comment by yossich6** [comment]
Hey, we saw that go mod file truly contains the new gin-gonic package v1.9.1 but go sum file still contains the cve version, gin-gonic v1.7.7. 
I think that you should run the command go mod tidy in order to clean the old version

see https://github.com/tbaehler/gin-keycloak/blob/master/go.sum:
line 679. github.com/gin-gonic/gin v1.7.7 h1:3DoBmSbJbZAWqXJC3SLjAPfutPJJRN1U5pALB7EeTTs=
line 680. github.com/gin-gonic/gin v1.7.7/go.mod h1:axIBovoeJpVj8S3BwE0uPMTeReE4+AfFtqpqaZ1qq1U=

**Comment by yossich6** [comment]
Hey @tbaehler , any updates?

**Comment by tbaehler** [comment]
at the moment not in the office, pnease create a PR I will approve it with my phoneAm 01.08.2023 um 10:30 schrieb Yossi Cherniak ***@***.***>:﻿
Hey @tbaehler , any updates?

**Comment by yossich6** [comment]
Hey @tbaehler , please approve the PR: https://github.com/tbaehler/gin-keycloak/pull/20
Thank you

**Comment by tbaehler** [comment]
approved thank you
