### ISSUE TITLE
How to make authentication?

### ISSUE THREAD

**Issue by protheusfr** [tbaehler/gin-keycloak#4]
Hello,

I'm really interested by your package, many thanks for you work, but it seem he manage only the authorization part not authentication.
I assume we can't do authorization management without authentication when we are in a traditional web app with human users, then how to manage OIDC authentication ?
Also can you give some keycloak configuration screenshot on authorization tabs that correspond to your exemple in order to help users to configure them accordingly ?

**Comment by tbaehler** [comment]
Hi 

I don't know if I get your question right, but I try... 
The provided package authorises requests based on a valid  jwt token in the request header. 
The package is not a OIDC or OAuth2 Server itself and does not generate jwt tokens. So you need a OAuth2 Server to authenticate your users, or you let your users authenticate with another oidc service like google/facebook/github whatever... 
As soon as you have your jwt token, you can do a request with your token to your go backend  and gin_keycloack will check the jwt token. 
You can check if the jwt token is just valid (user is authenticated) or if the user belongs to a specific role

Does this answer your question?

**Comment by protheusfr** [comment]
Yes, in fact this is API usage of Gin framework oriented.
Keycloak manage authorization but also authentication.
In the case of Gin app with a user UI, keycloak can manage login ui and token delivery.
I'm looking for a lib that manage both authentication and authorization via keycloak from Gin... and it seem difficult to find :)

**Comment by tbaehler** [comment]
But if you have keycloak in place… all you need to do is redirect the user to the keycloak login ui to authenticate. And then with the token redirect to your service page again right?

**Comment by protheusfr** [comment]
Yes via an OIDC lib and a way to store properly the token in user's session. I think I'll try to do myself.

**Comment by tbaehler** [comment]
Ok

the library is designed to work with single page app frameworks like angular react or vuejs… and there are libs that handles redirects to an oauth server and store the toke in the browser session. 

If you want to have the token server side in a http session, you will loose single sing on, and fault tolerence (user needs to relogin at server failure) 
but of course it is doable… 
to be honest, I don’t think this is a very clever idea… maybe the reason why you do not find a framework for that? 
But of corse you can go for it…
