### ISSUE TITLE
Realm roles

### ISSUE THREAD

**Issue by bianchinirick** [tbaehler/gin-keycloak#8]
The mapped token can't provides a way to see the realm roles. There is no option to validate the realm roles

**Comment by tbaehler** [comment]
You mean - you wish a easier way than
token.KeyCloakToken.ResourceAccess[<your service name>]?

**Comment by bianchinirick** [comment]
I think that token.CKeyCloakToken.ResourceAccess refers to ClientRoles, I need a way to use RealmRoles.
There is a RealmAccess See the sample below (jwt decripted from jwt.io):
{
  "exp": 1601464793,
  "iat": 1601464493,
 ...
  ],
  "sub": "7ed34707-d23b-4906-906d-3fb7f6914f2b",
  "typ": "Bearer",
  "azp": "middle",
  "session_state": "ecaf2c65-c68d-49f4-b567-6ea55b8f841e",
  "acr": "1",
  "allowed-origins": [
    "*"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "admin",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "realm-management": {
      "roles": [
        "view-identity-providers",
        "view-realm"
      ]
    },
    "middle": {
      "roles": [
        "uma_protection",
        "admin"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "view-applications",
        "view-consent",
        "manage-account-links",
        "manage-consent",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "clientId": "middle",
  "email_verified": false,
  "clientHost": "172.22.0.1",
  "preferred_username": "service-account-middle",
  "clientAddress": "172.22.0.1"
}

It's a common way to put some roles on realm. And this roles can be validated too.

**Comment by tbaehler** [comment]
Ok I understand. Will do a new release at saturday and try to address it.

**Comment by tbaehler** [comment]
v1.1.3 with realm support is released. pls let me know if it works for you.

**Comment by bianchinirick** [comment]
I have no words to thank you man!
I saw the code and everything looks fine.  I will change the version this week, But you can close this bug.
Thank you!
